### PR TITLE
change lodash imports

### PR DESCRIPTION
**Pull request by bytewiz**
avoid importing all of lodash only the fragments needed

replacing
```
import { get, set, clone } from "lodash";
```
with:
```
const get = require("lodash.get");
const set = require("lodash.set");
const clone = require("lodash.clone");
```

- [x] No errors `npm run build`
- [x] No errors `npm run test`

### CODE REVIEW

**Comment by MichalZalecki** [comment]
@bytewiz Thanks. I'll later test and publish new version on npm.

**Comment by MichalZalecki** [comment]
@bytewiz I'd like to avoid installing "per function" libs as those are quite hairy . Can you keep the `lodash` and change imports to:

```js
import get = require("lodash/get");
import set = require("lodash/set");
import clone = require("lodash/clone");
```

I'll be happy to merge your PR.

**Comment by bytewiz** [comment]
@MichalZalecki alright, I understand I will fix that 👍

**Comment by bytewiz** [comment]
@MichalZalecki please review it and let me know if that resolved it 👍 

seems to pass all tests etc. with no issues 💯

**Comment by MichalZalecki** [comment]
@bytewiz Can you use `import` instead of `const`?

```
> npm run lint
...
src/lib/mappet.ts[1, 13]: require statement not part of an import statement
src/lib/mappet.ts[2, 13]: require statement not part of an import statement
src/lib/mappet.ts[3, 15]: require statement not part of an import statement
```

**Comment by bytewiz** [comment]
@MichalZalecki oh yea, let me just try 👍

**Comment by bytewiz** [comment]
@MichalZalecki Seem to work without any complications 👍 just forgot to change that before.

**Comment by MichalZalecki** [comment]
@bytewiz Awesome, thanks! 🙌

**Pull request merged**
